# Use the CUDA image as the base image
FROM nvidia/cuda:12.1.0-cudnn8-devel-ubuntu22.04

# Set labels
LABEL com.danswer.maintainer="founders@danswer.ai"
LABEL com.danswer.description="This image is for the Danswer model server which runs all of the \
AI models for Danswer. This container and all the code is MIT Licensed and free for all to use. \
You can find it at https://hub.docker.com/r/danswer/danswer-model-server. For more details, \
visit https://github.com/danswer-ai/danswer."

# Default DANSWER_VERSION, typically overridden during builds by GitHub Actions
ARG DANSWER_VERSION=0.3-dev
ENV DANSWER_VERSION=${DANSWER_VERSION} \
    DANSWER_RUNNING_IN_DOCKER="true"

RUN echo "DANSWER_VERSION: ${DANSWER_VERSION}"

# Install basic dependencies and Python packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    python3-pip \
    git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Create a symbolic link for python pointing to python3
RUN ln -s /usr/bin/python3 /usr/bin/python

# Install PyTorch and other required dependencies
RUN pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

# Install packaging and ninja
RUN pip install --no-cache-dir packaging ninja

# Verify ninja installation
RUN ninja --version && echo $? || (pip uninstall -y ninja && pip install ninja)

# Install flash-attn
RUN pip install flash-attn --no-build-isolation

# Pre-download models for setups with limited egress
RUN python -c "from transformers import AutoTokenizer; \
AutoTokenizer.from_pretrained('distilbert-base-uncased'); \
AutoTokenizer.from_pretrained('mixedbread-ai/mxbai-rerank-xsmall-v1'); \
from huggingface_hub import snapshot_download; \
snapshot_download(repo_id='danswer/hybrid-intent-token-classifier', revision='v1.0.3'); \
snapshot_download('nomic-ai/nomic-embed-text-v1'); \
snapshot_download('mixedbread-ai/mxbai-rerank-xsmall-v1'); \
from sentence_transformers import SentenceTransformer; \
SentenceTransformer(model_name_or_path='nomic-ai/nomic-embed-text-v1', trust_remote_code=True);"

# Move the Hugging Face cache to prevent overwriting if volumes are mounted
RUN mv /root/.cache/huggingface /root/.cache/temp_huggingface

WORKDIR /app

# Copy utility scripts and models
COPY ./danswer/utils/logger.py /app/danswer/utils/logger.py
COPY ./danswer/__init__.py /app/danswer/__init__.py
COPY ./shared_configs /app/shared_configs
COPY ./model_server /app/model_server

ENV PYTHONPATH=/app

# Start the model server
CMD ["uvicorn", "model_server.main:app", "--host", "0.0.0.0", "--port", "9000"]

